title:              0xMohammed
email:              0xmohammedhassan@gmail.com
description:        Technical Writeups and tools
author:             0xMohammed
baseurl:            "/"
url:                "https://0xmohammed.github.io"

# Social Profiles
twitter_username:   0xMohamedhassan
github_username:    0xMohammed
facebook_username:  0xMohammed
instagram_username:  
linkedin_username:  mohammed-hassan-b94956186

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-178652732-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
